# -*- coding: utf-8 -*-
"""data_preparation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dp-sE3YohwZi6dQ6Y4m35fYvbX352zFY
"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import random
import os

random.seed(2024)
np.random.seed(2024)

from google.colab import drive
drive.mount('/content/drive')

RAW_PATH = ""   # place CMS files in same folder as this script
OUT_PATH = ""   # output files will appear in same folder

import os

print(os.listdir(RAW_PATH))

os.makedirs(RAW_PATH, exist_ok=True)
os.makedirs(OUT_PATH, exist_ok=True)

#Processing Hospital General Information
hospital_df = pd.read_csv(RAW_PATH + "Hospital_General_Information.csv", dtype=str)
hospital_df.columns = hospital_df.columns.str.strip()

print(hospital_df.columns)

dim_hospital = hospital_df[[
    "Facility ID",
    "Facility Name",
    "Address",
    "City/Town",
    "State",
    "ZIP Code",
    "County/Parish",
    "Telephone Number",
    "Hospital Type",
    "Hospital Ownership",
    "Emergency Services",
    "Hospital overall rating"
]].copy()

dim_hospital.columns = [
    "FacilityID", "HospitalName", "Address", "City", "State",
    "ZipCode", "County", "Phone", "HospitalType",
    "Ownership", "EmergencyServices", "OverallRating"
]

hospital_df.head()

dim_hospital.shape

hospital_df.info()

# Clean overall rating (CMS uses "Not Available" for missing)
dim_hospital["OverallRating"] = pd.to_numeric(
    dim_hospital["OverallRating"].replace("Not Available", np.nan),
    errors="coerce"
)

dim_hospital["OverallRating"].head(10)

dim_hospital["OverallRating"].isna().sum()

dim_hospital["OverallRating"].describe()

dim_hospital["OverallRating"].value_counts(dropna=False)

# Add region
region_map = {
    "ME":"Northeast","NH":"Northeast","VT":"Northeast","MA":"Northeast",
    "RI":"Northeast","CT":"Northeast","NY":"Northeast","PA":"Northeast","NJ":"Northeast",
    "OH":"Midwest","MI":"Midwest","IN":"Midwest","IL":"Midwest","WI":"Midwest",
    "MN":"Midwest","IA":"Midwest","MO":"Midwest","ND":"Midwest","SD":"Midwest",
    "NE":"Midwest","KS":"Midwest",
    "DE":"South","MD":"South","DC":"South","VA":"South","WV":"South",
    "NC":"South","SC":"South","GA":"South","FL":"South","KY":"South",
    "TN":"South","AL":"South","MS":"South","AR":"South","LA":"South",
    "OK":"South","TX":"South",
    "MT":"West","ID":"West","WY":"West","CO":"West","NM":"West",
    "AZ":"West","UT":"West","NV":"West","WA":"West","OR":"West",
    "CA":"West","AK":"West","HI":"West"
}

print(region_map["TX"])
print(region_map["CA"])

dim_hospital["Region"] = dim_hospital["State"].map(region_map).fillna("Territory")
dim_hospital["IsEmergencyHospital"] = (dim_hospital["EmergencyServices"] == "Yes").astype(int)

dim_hospital[["State","Region"]].head()
dim_hospital["Region"].value_counts()

dim_hospital[["EmergencyServices","IsEmergencyHospital"]].head()
dim_hospital["IsEmergencyHospital"].value_counts()

dim_hospital.to_csv(OUT_PATH + "DimHospital.csv", index=False)
print("Saved DimHospital.csv")

#Processing Quality Measures

# --- Readmission & Mortality ---
comp= pd.read_csv(RAW_PATH + "Complications_and_Deaths-Hospital.csv", dtype=str)
comp.columns = comp.columns.str.strip()

comp.head()

comp["Measure ID"].value_counts().head(20)

key_measures = {
    "MORT_30_AMI": "Heart Attack 30-Day Mortality",
    "MORT_30_CABG": "CABG 30-Day Mortality",
    "MORT_30_COPD": "COPD 30-Day Mortality",
    "MORT_30_HF": "Heart Failure 30-Day Mortality",
    "MORT_30_PN": "Pneumonia 30-Day Mortality",
    "MORT_30_STK": "Stroke 30-Day Mortality",

    "COMP_HIP_KNEE": "Hip/Knee Complication Rate",

    "PSI_03": "Pressure Ulcer Rate",
    "PSI_04": "Death Rate from Treatable Surgical Complications",
    "PSI_06": "Iatrogenic Pneumothorax Rate",
    "PSI_08": "Fall with Hip Fracture Rate",
    "PSI_09": "Perioperative Hemorrhage Rate",
    "PSI_10": "Postoperative Acute Kidney Injury Rate",
    "PSI_11": "Postoperative Respiratory Failure Rate",
    "PSI_12": "Pulmonary Embolism/DVT Rate",
    "PSI_13": "Postoperative Sepsis Rate",
    "PSI_14": "Postoperative Wound Dehiscence Rate",
    "PSI_15": "Accidental Puncture/Laceration Rate",
    "PSI_90": "Patient Safety Composite Score"
}

comp_filtered = comp[comp["Measure ID"].isin(key_measures.keys())][
    ["Facility ID", "Measure ID", "Score", "Compared to National"]
].copy()

comp_filtered.columns = ["FacilityID","MeasureID","Score","ComparedToNational"]

comp_filtered["MeasureName"]= comp_filtered["MeasureID"].map(key_measures)

comp_filtered.head()

def get_category(measure_id):
    if "MORT" in measure_id:
        return "Mortality"
    elif "PSI" in measure_id:
        return "Patient Safety"
    else:
        return "Complication"

comp_filtered["MeasureCategory"] = comp_filtered["MeasureID"].apply(get_category)

comp_filtered["Score"] = pd.to_numeric(comp_filtered["Score"].replace("Not Available", np.nan), errors="coerce")

comp_filtered[["MeasureID", "MeasureCategory"]].head(20)

comp_filtered["MeasureCategory"].value_counts()

#  HCAHPS Satisfaction
hcahps = pd.read_csv(RAW_PATH + "HCAHPS-Hospital.csv", dtype=str)
hcahps.columns = hcahps.columns.str.strip()

hcahps.head()

hcahps.shape

satisfaction_measures = {
    "H_COMP_1_A_P":  "Nurse Communication - Always",
    "H_COMP_2_A_P":  "Doctor Communication - Always",
    "H_CLEAN_HSP_A_P": "Room Cleanliness - Always",
    "H_QUIET_HSP_A_P": "Hospital Quietness - Always",
    "H_RECMND_DY":     "Definitely Recommend",
    "H_RATING_9_10":   "Rating 9 or 10 out of 10",
}

hcahps_filtered = hcahps[hcahps["HCAHPS Measure ID"].isin(satisfaction_measures.keys())][
    ["Facility ID", "HCAHPS Measure ID", "Patient Survey Star Rating", "HCAHPS Answer Percent"]
].copy()

hcahps_filtered.columns = [
    "FacilityID",
    "MeasureID",
    "StarRating",
    "AnswerPercent"
]

hcahps_filtered["MeasureName"] = hcahps_filtered["MeasureID"].map(satisfaction_measures)

hcahps_filtered[["MeasureID","MeasureName"]].head()

hcahps_filtered["MeasureCategory"] = "Patient Satisfaction"

hcahps_filtered["MeasureCategory"].head(20)

hcahps_filtered["MeasureCategory"].value_counts()

hcahps_filtered["Score"] = pd.to_numeric(
    hcahps_filtered["AnswerPercent"].replace("Not Available", np.nan), errors="coerce"
)

hcahps_filtered["ComparedToNational"] = np.nan

hcahps_filtered["ComparedToNational"].head()

hcahps_filtered = hcahps_filtered[["FacilityID","MeasureID","Score","ComparedToNational","MeasureName","MeasureCategory"]]

hcahps_filtered.columns

print("Rows:", len(hcahps_filtered))

# --- Timely & Effective Care (ER measures) ---
timely = pd.read_csv(RAW_PATH + "Timely_and_Effective_Care-Hospital.csv", dtype=str)
timely.columns = timely.columns.str.strip()

timely.info()

timely.head()

timely["Measure ID"].unique()

timely["Measure ID"].value_counts()

er_measures = {
    "OP_18a": "Median ER Time Before Departure",
    "OP_18b": "Median Time to Pain Management",
    "OP_18c": "Median Time to Diagnostic Evaluation",
    "OP_18d": "Median Time to Transfer",
    "OP_22": "Left Without Being Seen (%)",
    "OP_23": "Head CT Results Within 45 Minutes",
    "OP_29": "Appropriate Follow-up After Colonoscopy",
    "OP_31": "Cataract Surgery Improvement Rate",
    "OP_40": "Influenza Vaccination Coverage",
    "SEP_1": "Sepsis Care Bundle Compliance (%)",
    "SAFE_USE_OF_OPIOIDS": "Safe Use of Opioids"
}

timely_filtered = timely[timely["Measure ID"].isin(er_measures.keys())][
    ["Facility ID", "Measure ID", "Score"]
].copy()

timely_filtered.columns = ["FacilityID","MeasureID","Score"]

timely_filtered["MeasureName"] = timely_filtered["MeasureID"].map(er_measures)

timely_filtered["MeasureCategory"]   = "Timeliness & Effectiveness"

timely_filtered["ComparedToNational"]= np.nan

timely_filtered[["MeasureID", "ComparedToNational"]].head()

timely_filtered["Score"] = pd.to_numeric(
    timely_filtered["Score"].replace("Not Available", np.nan), errors="coerce"
)

timely_filtered["Score"].dtype

print(timely_filtered.shape)

timely_filtered[["MeasureID","MeasureName"]].head()

# Combine all quality measures
fact_quality = pd.concat(
    [comp_filtered, hcahps_filtered, timely_filtered],
    ignore_index=True
)

fact_quality["MeasureCategory"].value_counts()

fact_quality.to_csv(OUT_PATH + "FactHospitalQuality.csv", index=False)
print(f"      Saved FactHospitalQuality.csv — {len(fact_quality):,} rows total")

import os

os.path.exists(
    OUT_PATH + "FactHospitalQuality.csv"
)

# Extracting real Facility IDs for patient supplement

# Sample 80 hospitals that have emergency services and a valid rating
sample_hospitals = dim_hospital[
    (dim_hospital["EmergencyServices"] == "Yes") &
    (dim_hospital["OverallRating"].notna())
].sample(80, random_state=42)

real_facility_ids = sample_hospitals["FacilityID"].tolist()
print(f"Selected real hospital IDs for supplement = {len(real_facility_ids)} ")

sample_hospitals.shape

# Generating DimDiagnosis

diagnoses = [
    ("D001","Acute Myocardial Infarction","I21","Cardiovascular","Critical",15000),
    ("D002","Heart Failure",              "I50","Cardiovascular","High",    8500),
    ("D003","Stroke",                     "I63","Neurological",  "Critical",12000),
    ("D004","Pneumonia",                  "J18","Respiratory",   "Medium",  6000),
    ("D005","COPD Exacerbation",          "J44","Respiratory",   "Medium",  5500),
    ("D006","Appendicitis",               "K35","Gastrointestinal","Low",   4200),
    ("D007","Hip Fracture",               "S72","Musculoskeletal","High",   11000),
    ("D008","Sepsis",                     "A41","Infectious",    "Critical",18000),
    ("D009","Acute Kidney Injury",        "N17","Renal",         "High",    13000),
    ("D010","Breast Cancer",              "C50","Oncology",      "High",    22000),
    ("D011","Colorectal Cancer",          "C18","Oncology",      "High",    19000),
    ("D012","Asthma Exacerbation",        "J45","Respiratory",   "Low",     3200),
    ("D013","Depression",                 "F32","Mental Health",  "Low",     2800),
    ("D014","Hypertensive Crisis",        "I10","Cardiovascular","Medium",  4500),
    ("D015","Normal Delivery",            "O80","Obstetrics",    "Low",     6000),
    ("D016","Cesarean Section",           "O82","Obstetrics",    "Medium",  9500),
    ("D017","Pediatric Fever",            "R50","Pediatric",     "Low",     2200),
    ("D018","Traumatic Brain Injury",     "S06","Neurological",  "Critical",25000),
    ("D019","Urinary Tract Infection",    "N39","Infectious",    "Low",     2400),
    ("D020","Gastrointestinal Bleed",     "K92","Gastrointestinal","High",  8000),
]
dim_diag = pd.DataFrame(diagnoses, columns=[
    "DiagnosisID","DiagnosisName","ICD10Code","DiagnosisCategory",
    "SeverityLevel","AvgTreatmentCostUSD"
])

dim_diag.head()

dim_diag.to_csv(OUT_PATH + "DimDiagnosis.csv", index=False)
print(f"Saved DimDiagnosis.csv — {len(dim_diag)} diagnoses")

# Generating FactAdmissions (50,000 rows using real hospital IDs)

diag_ids       = [d[0] for d in diagnoses]
diag_severity  = {d[0]: d[4] for d in diagnoses}
diag_cost_base = {d[0]: d[5] for d in diagnoses}
diag_category  = {d[0]: d[3] for d in diagnoses}

diag_ids[:5]

diag_severity['D001']

severity_los   = {"Low": (1,3), "Medium": (3,7), "High": (5,14), "Critical": (7,30)}
severity_mort  = {"Low": 0.002, "Medium": 0.012, "High": 0.05,   "Critical": 0.12}
admit_types    = ["Emergency","Elective","Urgent","Maternity","Transfer"]
admit_weights  = [0.38, 0.28, 0.20, 0.08, 0.06]
discharge_opts = ["Recovered","Discharged - Follow Up","Referred","Deceased","Against Medical Advice"]
insurance_opts = ["Medicare","Medicaid","Private - BlueCross","Private - Aetna",
                  "Private - Cigna","Uninsured","Private - UnitedHealth"]

rows = []
for i in range(50000):
    diag_id   = random.choice(diag_ids)
    sev       = diag_severity[diag_id]
    los_range = severity_los[sev]
    mort_prob = severity_mort[sev]
    base_cost = diag_cost_base[diag_id]

    facility_id = random.choice(real_facility_ids)

    admit_date = datetime(2020, 1, 1) + timedelta(days=random.randint(0, 1826))
    los_days   = random.randint(*los_range) + random.randint(-1, 3)
    los_days   = max(0, min(los_days, 60))
    disch_date = admit_date + timedelta(days=los_days)

    admit_type = random.choices(admit_types, weights=admit_weights)[0]
    age_group  = random.choices(
        ["0-17","18-34","35-54","55-74","75+"],
        weights=[0.08, 0.15, 0.22, 0.30, 0.25]
    )[0]
    gender     = random.choice(["Male","Female","Other"])
    insurance  = random.choice(insurance_opts)

    if "Private" in insurance:  cov = random.uniform(0.70, 0.95)
    elif insurance == "Medicare": cov = random.uniform(0.75, 0.90)
    elif insurance == "Medicaid": cov = random.uniform(0.80, 0.95)
    else:                         cov = random.uniform(0.00, 0.15)

    total_cost    = round(base_cost * random.uniform(0.75, 1.25) + los_days * random.uniform(500, 1500), 2)
    ins_revenue   = round(total_cost * cov, 2)
    out_of_pocket = round(total_cost - ins_revenue, 2)

    if age_group == "75+": mort_prob *= 1.6
    is_deceased = random.random() < mort_prob
    if is_deceased:
        disch_status = "Deceased"
    else:
        disch_status = random.choices(
            ["Recovered","Discharged - Follow Up","Referred","Against Medical Advice"],
            weights=[0.55, 0.30, 0.12, 0.03]
        )[0]

    readmit_base = 0.08
    if diag_id in ["D002","D005","D009"]: readmit_base = 0.18
    if age_group == "75+":               readmit_base *= 1.4
    is_readmit = 1 if random.random() < readmit_base else 0

    er_wait = None
    if admit_type == "Emergency":
        er_wait = int(np.random.lognormal(3.5, 0.6))
        er_wait = max(5, min(er_wait, 480))

    satisfaction = round(max(1, min(10, 7.2 + random.gauss(0, 1.2))), 1)

    rows.append({
        "AdmissionID":         f"ADM{100000+i}",
        "FacilityID":          facility_id,
        "DiagnosisID":         diag_id,
        "AdmissionDate":       admit_date.strftime("%Y-%m-%d"),
        "DischargeDate":       disch_date.strftime("%Y-%m-%d"),
        "AdmissionType":       admit_type,
        "AgeGroup":            age_group,
        "Gender":              gender,
        "InsuranceType":       insurance,
        "LengthOfStayDays":    los_days,
        "ERWaitTimeMinutes":   er_wait,
        "DischargeStatus":     disch_status,
        "IsReadmission":       is_readmit,
        "SatisfactionScore":   satisfaction,
        "TotalCostUSD":        total_cost,
        "InsuranceRevenueUSD": ins_revenue,
        "OutOfPocketUSD":      out_of_pocket,
    })

fact_admissions = pd.DataFrame(rows)
fact_admissions.to_csv(OUT_PATH + "FactAdmissions.csv", index=False)
print(f"      Saved FactAdmissions.csv — {len(fact_admissions):,} rows")

fact_admissions.shape

fact_quality.shape

fact_quality.head()

fact_quality.info()

fact_quality["MeasureCategory"].value_counts()

fact_quality["MeasureName"].isna().sum()

fact_quality[
    fact_quality["MeasureCategory"] == "Timeliness & Effectiveness"
]["MeasureName"].isna().sum()

timely_filtered[
    timely_filtered["MeasureName"].isna()
]["MeasureID"].unique()

fact_quality.isna().sum()

fact_quality.groupby("MeasureCategory")["Score"].apply(lambda x: x.isna().sum())

fact_quality.groupby("MeasureCategory")["ComparedToNational"].apply(lambda x: x.isna().sum())

fact_quality.describe(include="all")

fact_quality.shape

fact_quality["MeasureCategory"].value_counts()

fact_quality["MeasureName"].nunique()

